### ISSUE TITLE
Microsoft Update Assistant failed to be managed by applied profile:notif.mobileconfig

### ISSUE THREAD

**Issue by IDCheryl** [microsoft/mdatp-xplat#101]
Hello Expert,

I tried the below link to apply allow notification to autoupdate on macOS.
However, i could see the notification profiles in my macOS, but toggle for "allow notification" can still be changed.
it can be reproduced on multiple devices, could you please kindly check?
https://raw.githubusercontent.com/microsoft/mdatp-xplat/master/macos/mobileconfig/profiles/notif.mobileconfig
![Screen Shot 2023-08-01 at 2 23 57 PM](https://github.com/microsoft/mdatp-xplat/assets/105334881/1e8e4678-46b9-4a01-853c-f6e84ba86012)
![9ed1cdcf-7624-4cf0-b128-714c5dbae573](https://github.com/microsoft/mdatp-xplat/assets/105334881/f2dc7a79-efe0-4a1f-9a38-379b3a742e3e)

**Comment by maximvelichko** [comment]
Your question is about Microsoft Auto Update, please direct it to the MAU project (by opening a support ticket)
