### ISSUE TITLE
How to set MDE/EPP from Passive mode to Active mode?

### ISSUE THREAD

**Issue by XXIVAVIXX** [microsoft/mdatp-xplat#123]
How to set MDE/EPP from Passive mode to Active mode?

**Comment by XXIVAVIXX** [comment]
--- mde_installer.sh v0.6.6 ---
[>] detected: rhel 8.8  (fedora)
[>] scaled: 8
[v] set package manager: yum
[>] MDE/EPP already in passive mode
[v] passive mode set
[S] MDE installed.
[S] Version: "101.23102.0003"
[S] Onboarded: true
[S] Passive mode: true
[S] Device tags: []
[S] Subsystem: "fanotify"
[S] Conflicting applications: []
[v] --- mde_installer.sh ended. ---
[*] exiting (0)

**Comment by maximvelichko** [comment]
You cannot do it with these tools

**Comment by XXIVAVIXX** [comment]
@maximvelichko Yhea thanks for your answer it's really really helpful!!!!!

For anyone that's looking for the right answer here is a link to the microsoft docs:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide
