### ISSUE TITLE
Tons of errors in MS documentation

### ISSUE THREAD

**Issue by tmpkn** [microsoft/mdatp-xplat#126]
The official Microsoft documentation (https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#step-14-download-the-onboarding-package) referencing the files in this repo is awfully messed up. Here are the issues I found:

- Step 1 / 1: not in Microsoft Defender portal, but in Endpoint/Intune portal
- Step 2 / 9: missing file selection
- Step 4 / 6: someone copypasted name from Step 3 (FullDiskAccess), it should say something like BackgroundService
- Step 4 / 8: again wrong suggested name (should be background_services.mobileconfig)
- Step 5 / 6: same issue as step 4/6
- Step 7: wrong github link (needs to be raw, as is downloads a github json)
- Step 7: doesn't mention that user should look for ChannelName in the XML to choose one of the channels (default set to Production, which is OK)
- Step 8: the "Microsoft Defender portal" link is all wrong and links to some weird place that requires a MS (non-365) account
- Step 11: why can't DLP be included in the .mobileconfig file we download in step4, also which .mobileconfig do we update with features/dataLossPrevention/enabled?
- Step 15: it would be nice to say we're switching back from Defender portal to Intune portal.
- Step 15 / 6+7: why are you callling it Autoupdate? that was Step 7. It should be something like "Licensing" or "Onboarding"
- Step 15 / 10: which effing file?? (it's the one in the intune directory inside the zip we downloaded in step 14)

**Comment by maximvelichko** [comment]
@tmpkn , please leave comments to corresponding pages directly. 
This repo is for open sourced tools for Defender for macOS and Linux only
