### ISSUE TITLE
packages repo misconfigured on RHEL 8 following latest PR125

### ISSUE THREAD

**Issue by EmFl** [microsoft/mdatp-xplat#128]
Hello,

Following PR  #125, the repo file that is created references an incorrect url on RHEL 8 systems (and maybe others ?) which gives the following error:

```
2024-02-15T10:12:27 INFO  [v] required pkgs are installed
2024-02-15T10:12:27 INFO  [i] repository already configured
2024-02-15T10:12:28 INFO  [>] installing MDE
2024-02-15T10:12:31 DEBUG [>] Running command: yum -y --enablerepo=packages-microsoft-com-prod install mdatp
2024-02-15T10:12:31 DEBUG [>] Command output: packages-microsoft-com-prod                     5.4  B/s |  14  B     00:02
Errors during downloading metadata for repository 'packages-microsoft-com-prod':
  - Status code: 404 for https://packages.microsoft.com/rhel/8.0/prod/repodata/repomd.xml
Error: Failed to download metadata for repo 'packages-microsoft-com-prod': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Looking at https://packages.microsoft.com/rhel/, the correct url should be 8 instead of 8.0

Would you be able to either revert or amend the change so that we get back a working installation of MDE extension on azure rhel 8 ?

Thank you !

**Comment by acheng-01** [comment]
Hello, packages.microsoft.com here. We have a note about the [creation of the 8.0 distribution endpoints](https://github.com/microsoft/linux-package-repositories/issues/113#issuecomment-1954776194) here that should resolve this issue as well. We did not have that 8.0 url when we thought we did. Apologies for any inconvenience this may have caused.

Thank you for your patience. Please post any additional issues regarding this topic in the [thread in our github repo](https://github.com/microsoft/linux-package-repositories/issues/113), as we will continue to monitor that for the next few days before closing it out.

**Comment by EmFl** [comment]
Hello,
Thanks for the follow up and quick fix !
