### ISSUE TITLE
Script fails - line 47: /etc/os-release: Permission denied

### ISSUE THREAD

**Issue by igarcia10** [microsoft/mdatp-xplat#13]
Hello.
The script was failing due to an empty elif on line 50.
After changing it to an else, I get this error message: 

--- mde_installer.sh v0.1 ---
verifying minimal reuirements: 1 cores, 1024 MB RAM, 1024 MB disk space
device qualifies
./mde_installer.sh: line 47: /etc/os-release: Permission denied

**Comment by mycodeself** [comment]
This [PR](https://github.com/microsoft/mdatp-xplat/pull/14) solves these issues
