### ISSUE TITLE
Error on Intune upload : Must be a well formed XML string  : Accessibility.mobileconfig

### ISSUE THREAD

**Issue by TimD1999** [microsoft/mdatp-xplat#133]
When following this guide to upload the accessibility.mobileconfig file we see an error "Must be a well formed XML string"

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#step-6-accessibility-settings

<img width="679" alt="image" src="https://github.com/microsoft/mdatp-xplat/assets/106993770/8273014d-fe05-4b0c-99b3-c352c575c87f">

**Comment by TrickyB** [comment]
Trying to configure MS Endpoint for MacOS in InTune but at step 6 i'm running into the same error and i can't convert the accessiblity.mobileconfig from html to xml (at the start of the config file it states **<!DOCTYPE html>** which results in the error mentioned above.

**Comment by TrickyB** [comment]
Never mind! 
[https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/accessibility.mobileconfig](url)
contains the proper XML accessibility.mobileconfig in XML format!

Thank you @Maximvelichko

**Comment by DannyJanmaat** [comment]
Save as UTF-8 WITHOUT BOM
