### ISSUE TITLE
high_cpu_parser.py is broken on Ubuntu Bionic

### ISSUE THREAD

**Issue by folti** [microsoft/mdatp-xplat#18]
Greetings,

Since MR #17, running `linux/high_cpu_parser.py` with the `--group 1` option on an Ubuntu Bionic system, with both stock versions of Python (2.7.17 and 3.6.9) results in the following error:

```
# python high_cpu_parser.py --group 1 < x.json
Traceback (most recent call last):
  File "high_cpu_parser.py.1", line 28, in <module>
    groups[name][0] = groups[name] + cnt
TypeError: unsupported operand type(s) for +: 'set' and 'int'
```

**Comment by jponf** [comment]
@folti I've created this PR https://github.com/microsoft/mdatp-xplat/pull/54, which should address this issue. 

But I don't know if they will ever consider merging it 🤷

**Comment by maximvelichko** [comment]
@folti , can you please try from @jponf 's branch and confirm that it resolves your issue?

**Comment by folti** [comment]
Hello, yes, it works on bionic now.

**Comment by jponf** [comment]
@folti and @maximvelichko, since https://github.com/microsoft/mdatp-xplat/pull/58 have been merged I believe this issue can be closed now :)
