### ISSUE TITLE
mde_installer broken by run_quietly function

### ISSUE THREAD

**Issue by collinjc** [microsoft/mdatp-xplat#25]
After the introduction of the run_quietly function, installation now hangs indefinitely unless -y is passed as an option to mde_installer. This is not terribly obvious to the user. While there are at least two potential solutions to this problem, I believe one is significantly better than the other.

### Solution 1 (easiest, but probably not the best one to go with)
The easiest solution is obviously to simply add a -y to any interactive command that is invoked by run_quietly. This will allow for the command to complete without prompting for user input. The major downside of this is that it is generally a bad idea to blindly perform package manager operations without explicit user confirmation. This brings me to Solution 2.

### Solution 2 (the _correct_ solution, in my opinion)
Interactive commands that are now invoked by run_quietly should only do so if -y is passed as an option to mde_installer. When -y is passed, the user is explicitly stating that they do not wish to be prompted for user input and that they are accepting whatever risks are associated with that choice.

**Comment by collinjc** [comment]
Any update on this?

**Comment by MatiAtMicrosoft** [comment]
issue is resolved

**Comment by collinjc** [comment]
I don't believe it is, actually. While I do see that my pull request was apparently merged in, it appears to have been obliterated, leaving the same broken functionality since the introduction of run_quietly. I have created a brand new machine running Fedora 35, checked out the current branch, and ran

> sudo ./mde_installer -i

and the script hangs indefinitely at

> [>] installing  yum-utils

As mentioned before, this is because run_quietly is suppressing the output of the command (in this case yum install yum-utils). Without ASSUMEYES being asserted yum and dnf (**most** package managers, I assume) require the user to respond with 'y' to proceed. I can only assume that you are either always running

> sudo ./mde_installer.sh -i -y

or you are running this on a machine that already has all of the required dependencies installed, and therefore does not need to invoke the package manager. Remember that neither of these cases are representative of the potential install-base. I'd certainly be happy to create another pull request to fix this functionality yet again, hopefully this time in a timely manner and without immediately removing the fix. In the meantime, this is a problem that is trivial to reproduce. Simply perform a fresh installation of your distro of choice, and execute mde_installer.sh without the -y option.
