### ISSUE TITLE
fulldiskaccess.mobileconfig not working properly

### ISSUE THREAD

**Issue by bhaap** [microsoft/mdatp-xplat#29]
It looks like even thou the profile is pushed to the user the system extension is not allowed Full Disk Access.

This is the latest download and pushed through intune as described in the microsoft docs.
![Screenshot 2021-11-09 at 13 39 24](https://user-images.githubusercontent.com/2168003/140926075-0b7c9bb8-6734-48ac-a4df-fcf8d273b2e2.png)
![Screenshot 2021-11-09 at 13 38 57](https://user-images.githubusercontent.com/2168003/140926085-5ad40d67-5f37-42d9-85c4-f4114eff0c43.png)

**Comment by maximvelichko** [comment]
@bhaap, from my experience macOS does not usually properly show full disk access granted via MDM. What you see in UI is most probably what is granted manually via UI.

You can read `/Library/Application Support/com.apple.TCC/MDMOverrides.plist` to get what was applied through MDM.
