### ISSUE TITLE
Jamf Pro 10.33.0: Changes to "Antivirus engine > Disallowed threat actions" not retained when saving

### ISSUE THREAD

**Issue by dan-snelson** [microsoft/mdatp-xplat#30]
First, thanks for providing such excellent documentation and resources.

When using the provided [JSON](https://github.com/microsoft/mdatp-xplat/blob/master/macos/schema/schema.json) in Jamf Pro 10.33.0, changes to "Antivirus engine > Disallowed threat actions" are not retained when saving.

Additionally, if "Antivirus engine > Disallowed threat actions" is configured before saving, _**no**_ modifications will be retained when saving.

---

Steps to reproduce:
1. Follow the steps as outlined in [Step 3: Configure Microsoft Defender for Endpoint settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-3-configure-microsoft-defender-for-endpoint-settings)
2. For Step 3.6, select:
    1. Antivirus engine > Add/Remove Properties > Disallowed threat actions > Apply
    2. Enable "allow" and "restore"
    3. Save the Configuration Profile
    4. Click Plist preview
    5. Observe that "Disallowed threat actions" remains un-configured 
3. Edit the Configuration Profile, adding all Antivirus engine properties and omitting "Disallowed threat actions"
4. Save the Configuration Profile
5. Click Plist preview
6. Observe that the plist is as expected
7. Repeat Step 2 and observe that "Disallowed threat actions" remains un-configured

**Comment by dan-snelson** [comment]
Confirming this issue persists with Jamf Pro `10.34.0-t1636381463`.

**Comment by maximvelichko** [comment]
I confirmed it too, please escalate it to JAMF support, it's an issue on their side.

**Comment by dan-snelson** [comment]
**PI-010345**
Description: Unable to edit Mac Configuration profile with the payload of Application & Custom Settings
 
 Steps to reproduce: 
 1. Create Configuration Profile
 - Jamf Pro > Computers > Configuration profiles > New > Application & Custom Settings > External Applications > `com.microsoft.wdav`
 2. Add > Antivirus engine properties > select all > edit settings
 3. Save
 
 **Workaround:** Use the Upload option instead with the complete setting in a plist
