### ISSUE TITLE
mde_installer is selecting ubuntu 18.04 when running on 22.04

### ISSUE THREAD

**Issue by BarbieroDB1** [microsoft/mdatp-xplat#47]
see these lines:
https://github.com/microsoft/mdatp-xplat/blob/a2a4164f98da865243ed83739f2c3f3f3267f08c/linux/installation/mde_installer.sh#L716-L717

mdatp is available for ubuntu jammy at https://packages.microsoft.com/ubuntu/22.04/prod/ so the installer script should probably allow 22.04 here instead of falling back to the bionic repo

**Comment by pmooo** [comment]
Seeing same issue. Submitted [Pull#48](https://github.com/microsoft/mdatp-xplat/pull/48) to resolve.

**Comment by agarwalneetu** [comment]
Hi @pmooo , I see you submitted a PR regarding this issue and it's been merged too. Can I go ahead and close this issue?

**Comment by quovide** [comment]
@agarwalneetu as requested the pull request

**Comment by agarwalneetu** [comment]
Resolved
