### ISSUE TITLE
Script is not working to offboard the VM from Defender / M365 Security portal

### ISSUE THREAD

**Issue by sunilsrinivas93** [microsoft/mdatp-xplat#5]
Hi Team
i am trying to offboard the VM from Defender Security portal using the script.
./mde_installer.sh -o <offboarding_script>
its showing output has VM successfully onboarded to console. 

Can you please confirm dose script will help to offboarding the VM ?

**Comment by MatiAtMicrosoft** [comment]
Hi @sunilsrinivas93,
Yes, the same message is being printed in both onboarding and offboarding case.
The best way to validate that offboarding was successful is by either:
* running `mdatp health` and expecting a message indicating license is missing, or
* running `mdatp health --field org_id` and expecting an empty string.

We'll fix the message - thanks!
hope this helps.
