### ISSUE TITLE
MDATP blocking his own installation

### ISSUE THREAD

**Issue by davesdere** [microsoft/mdatp-xplat#51]
Hi,
I have noticed that [mde_installer.sh](https://github.com/microsoft/mdatp-xplat/blob/master/linux/installation/mde_installer.sh) will throw the error below if it is already installed but not succesfully onboarded or if it is running a very old version.
```
[x] found conflicting applications: [/opt/microsoft/mdatp/sbin/wdavdaemon], aborting
```

My fix was to uninstall mdatp and run the script again. A quick fix in the script would be to add a line [here](https://github.com/microsoft/mdatp-xplat/blob/master/linux/installation/mde_installer.sh#L407) to verify if it is mdatp that blocks itself and just uninstall it automatically. 

**ENV**
```
h-4.2$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

sh-4.2$ mdatp version
Product version: 101.62.74
sh-4.2$
```

Hopefully someone can tackle that soon.
Thank you

**Comment by agarwalneetu** [comment]
@SvenMarquardt5772, please close this issue

**Comment by SvenMarquardt5772** [comment]
@agarwalneetu this not my issue but the one from @davesdere.

**Comment by davesdere** [comment]
@agarwalneetu Was it fixed? I can't check right now.

**Comment by SvenMarquardt5772** [comment]
There appears to be no commit indicating a fix.

**Comment by davesdere** [comment]
Thank you. Closing the ticket won't solve the issue neither. @agarwalneetu I still the errror.

**Comment by agarwalneetu** [comment]
PR raised for this bug : #77

**Comment by agarwalneetu** [comment]
@davesdere , please review the PR and close this bug accordingly
