### ISSUE TITLE
Documentation does not describe how to offboard and remove the product

### ISSUE THREAD

**Issue by mikeelliottuk** [microsoft/mdatp-xplat#55]
Hi,

The installer script options show that the -o|--onboard option can be used to onboard and offboard the device from the MDE service using the onboarding script.  Could you please clarify that the above switch and same onboarding script will in fact offboard a server that is currently onboarded?  If possible could you provide an example command line for offboarding and product removal?

Many thanks

**Comment by agarwalneetu** [comment]
fixed by #81
