### ISSUE TITLE
Rasberry Pi 

### ISSUE THREAD

**Issue by RyanMesser** [microsoft/mdatp-xplat#61]
Hi,

Not sure if Raspberry Pi's are supported? Running Ubuntu 22.04.1 LTS on arm64. 

I just get unable to locate package when trying to install package, the lists are installed along with the GPG key.

**Comment by maximvelichko** [comment]
@RyanMesser, this is not a product support channel.
(I don't see ARM arch packages [as being released](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/mdatp/), though I can be totally wrong here.)
