### ISSUE TITLE
apt key is depreciated

### ISSUE THREAD

**Issue by peteblank** [microsoft/mdatp-xplat#70]
It says that apt key is depreciated and I waited too long for it to install. Like over 1 hour. Ideally it should have a progress bar or something to tell you how long its going to take to install. I ended up doing it manually.  I also have pop os 22.04 which is based on ubuntu 22.04 so I had to change a couple of variables to make it run.

**Comment by agarwalneetu** [comment]
@peteblank, Hi I was planning to work on this issue, can you explain me in detail about this issue?

**Comment by agarwalneetu** [comment]
@peteblank

**Comment by agarwalneetu** [comment]
@peteblak, please provide more inffo on this issue. Closing it for now.
