### ISSUE TITLE
Install runs (failing) on ARM architacure

### ISSUE THREAD

**Issue by snoopotic** [microsoft/mdatp-xplat#74]
the mde_installer.sh script does not check on which cpu architecture the system is running.

I tried it on an ubuntu aarch64 and thus it runs and fails with:
`--- mde_installer.sh v0.5.10 ---
[v] minimal requirements met
[>] detected: ubuntu 20.04 focal (debian)
[>] scaled: 20.04
[v] set package manager: apt
/usr/bin/wget
[final] connected=OK
[v] connected
[v] no conflicting applications found
[v] required pkgs are installed
[>] installing MDE
[>] Running command: apt  -t focal install mdatp
[>] Command output: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mdatp
100
[>] Command exit_code: 100
[S] MDE not installed.
[x] unable to install MDE (1)
[*] exiting (21)
`

Of course: there is no arm package yet. 
The installer script should Fail on Beginning.

**Comment by agarwalneetu** [comment]
fixed in #81
