### ISSUE TITLE
Profiles for other Microsoft tools

### ISSUE THREAD

**Issue by KRi570F** [microsoft/mdatp-xplat#78]
I know this is the wrong place to ask but, it would be nice to have the same kind of mobileconfig profiles for other applications like these for Defender.
I noticed that these are also listed since macOS 13.x.x

![image](https://user-images.githubusercontent.com/3668792/221160880-0ca01b05-cee7-403a-a8fe-515bd2ab5c2e.png)
according to me these are also essential certenly full disk access.

- com.microsoft.autoupdate
- Microsoft Intune Agent
- OneDrive or just any other Microsoft 365 app

**Comment by maximvelichko** [comment]
Indeed, it is not related to Defender for macOS. Please find the product's GitHub repositories/learn.microsoft.com pages with similar information.
