### ISSUE TITLE
Default installation folder

### ISSUE THREAD

**Issue by kunamashina** [microsoft/mdatp-xplat#79]
So far I didn't manage to find a way on how to change the destination folder for the installation of mdatp with mde.installer.sh. Is it possible at all?

![image](https://user-images.githubusercontent.com/23556119/222741723-bb712291-8a8a-4f4e-8b04-73412e82d59a.png)

**Comment by drscript0x0** [comment]
From what I'm reading in the documentation (https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide) it says: "It is not supported to install Microsoft Defender for Endpoint in any other location other than the default install path."
