### ISSUE TITLE
Script does not support Amazon Linux distros. Are any plans to support it ?

### ISSUE THREAD

**Issue by mguja-fcc** [microsoft/mdatp-xplat#8]

**Comment by mguja-fcc** [comment]
sudo ./mde_installer.sh -i
--- mde_installer.sh v0.1 ---
Distro detected: amzn
Scaled version: 2
Unsupported distro

**Comment by allenkarns** [comment]
I just created a pull request that adds support for AL2, I'm not sure if they'll merge it or not. You're welcome to grab it from my fork though. 

https://github.com/allenkarns/mdatp-xplat

**Comment by maximvelichko** [comment]
I've merged a change from @allenkarns  into master, thanks for contribution!
