### ISSUE TITLE
Intune FullDisk Access mobileconfig does not enable Setting

### ISSUE THREAD

**Issue by flymg** [microsoft/mdatp-xplat#87]
I have installed the `macos/mobileconfig/profiles/fulldisk.mobileconfig` and deployed it via Intune.

Although it gets transfered to the device, the mac that has the profile installed shows both Defender and Extension with no FullDisk Access:

![Untitled](https://github.com/microsoft/mdatp-xplat/assets/19909203/7d07a506-a878-4528-8177-68c46e90e132)

Is this profile still operational?
Is Defender for Endpoint able to access full disk for scanning and protection with these two settings disabled?

macOS 13.4 (22F66) Ventura on m1 max
<img width="254" alt="image" src="https://github.com/microsoft/mdatp-xplat/assets/19909203/0b172b8a-83bc-44fb-88d8-eac1f0be447e">

**Comment by maximvelichko** [comment]
The full disk access profile is operational.
See [https://community.jamf.com/t5/jamf-pro/macos-ventura-full-disk-access/td-p/276764](for explanation)
